# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 4

empty-blocks:
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

style:
  ReturnCount:
    active: false
  ForbiddenComment:
    active: false
